name: sspc
channels: [conda-forge]
dependencies:
    - python=3.13
    - numpy
    - astropy
    - scipy
    - matplotlib
    - ipykernel
    - ipython
    - jupyter
    - ipydatagrid
    - h5py
    - pandas
    - black
    - isort
    - azure-identity
    - azure-storage-blob
    - requests
    - pre-commit
    - pip
